import type {
  ActionItem,
  ProjectObject,
  RoleView,
} from "@/domain/types";

function iso(d: Date): string {
  return d.toISOString();
}

const now = new Date();

function baseAction(
  id: string,
  projectId: string,
  stage: ActionItem["sourceStage"],
  overrides: Partial<ActionItem> & Pick<ActionItem, "title" | "summary">,
): ActionItem {
  return {
    id,
    createdAt: iso(now),
    updatedAt: iso(now),
    sourceProjectId: projectId,
    sourceStage: stage,
    goal: overrides.goal ?? "推进商品经营目标",
    title: overrides.title,
    summary: overrides.summary,
    expectedImpact: overrides.expectedImpact ?? "待评估",
    risk: overrides.risk ?? "medium",
    owner: overrides.owner ?? "system",
    approvalStatus: overrides.approvalStatus ?? "pending",
    executionMode: overrides.executionMode ?? "agent",
    executionStatus: overrides.executionStatus ?? "queued",
    requiresHumanApproval:
      overrides.requiresHumanApproval ?? true,
    triggeredBy: overrides.triggeredBy ?? "scenario_agent",
  };
}

function buildSeedProjects(): ProjectObject[] {
  return [
    {
      id: "proj_demo_oppo",
      createdAt: iso(now),
      updatedAt: iso(now),
      type: "opportunity_project",
      name: "秋冬系列商机包",
      stage: "opportunity_pool",
      owner: "u_growth_lead",
      stakeholders: [
        { id: "u_ceo", name: "老板", role: "ceo" },
        { id: "u_rd", name: "产品研发总监", role: "product_rd_director" },
      ],
      priority: 72,
      health: "watch",
      riskLevel: "medium",
      targetSummary: "验证市场需求信号与履约可行性",
      statusSummary: "商机池评估中，待经营决策排序",
      latestPulse: "2 条高风险待审批，竞品上新加速",
      keyBlocker: "样品交期不确定",
      kpis: {
        updatedAt: iso(now),
        metrics: [
          {
            key: "launch_score",
            label: "商机评分",
            value: 64,
            unit: "score",
            trend: "flat",
            freshness: "near_real_time",
          },
        ],
      },
      opportunityAssessment: {
        businessValueScore: 64,
        feasibilityScore: 58,
        expressionPotentialScore: 70,
        confidence: "medium",
        recommendation: "evaluate",
      },
      actions: [
        baseAction("act_oppo_1", "proj_demo_oppo", "opportunity_pool", {
          title: "立项评审：秋冬系列",
          summary: "建议进入新品孵化，待您审批",
          approvalStatus: "pending",
          triggeredBy: "decision_brain",
        }),
      ],
      agentStates: [
        {
          id: "ag_1",
          createdAt: iso(now),
          updatedAt: iso(now),
          projectId: "proj_demo_oppo",
          agentType: "opportunity",
          status: "running",
          summary: "扫描渠道与竞品信号",
        },
      ],
    },
    {
      id: "proj_incubation",
      createdAt: iso(now),
      updatedAt: iso(now),
      type: "new_product_project",
      name: "轻薄羽绒新品线",
      stage: "new_product_incubation",
      owner: "u_rd_lead",
      stakeholders: [
        { id: "u_rd", name: "产品研发总监", role: "product_rd_director" },
      ],
      priority: 70,
      health: "healthy",
      riskLevel: "low",
      targetSummary: "Q4 上架，主打通勤场景",
      statusSummary: "打样中，物料询价已回",
      keyBlocker: undefined,
      kpis: {
        updatedAt: iso(now),
        metrics: [
          {
            key: "launch_score",
            label: "孵化健康度",
            value: 78,
            unit: "score",
            trend: "up",
            freshness: "near_real_time",
          },
        ],
      },
      decisionObject: {
        id: "dec_inc_low",
        createdAt: iso(now),
        updatedAt: iso(now),
        projectId: "proj_incubation",
        stage: "new_product_incubation",
        problemOrOpportunity: "是否维持当前克重与充绒配比",
        rationale: "成本上行与保暖卖点平衡证据不足",
        options: [
          {
            id: "inc_o1",
            title: "维持现款",
            summary: "不改规格，压缩其它成本项",
            expectedImpact: "交付节奏最稳",
            risk: "medium",
            resourcesNeeded: "采购协同",
            validationWindow: "7 天",
            autoExecutable: false,
          },
        ],
        confidence: "low",
        requiresHumanApproval: true,
        evidencePack: { refs: [] },
      },
      definition: {
        id: "def_inc_1",
        createdAt: iso(now),
        updatedAt: iso(now),
        projectId: "proj_incubation",
        positioning: "都市轻保暖",
        targetAudience: "25–35 岁通勤白领",
        keySellingPoints: ["轻量", "可机洗"],
        priceBand: "299–399",
        specsSummary: "90 白鸭绒，20D 面料",
        feasibilityRisk: "medium",
        samplingStatus: "in_progress",
      },
      actions: [
        baseAction("act_inc_signoff", "proj_incubation", "new_product_incubation", {
          title: "打样评审会签",
          summary: "供应链与研发双签，待您审批",
          approvalStatus: "pending",
          triggeredBy: "human",
        }),
      ],
      agentStates: [
        {
          id: "ag_inc_1",
          createdAt: iso(now),
          updatedAt: iso(now),
          projectId: "proj_incubation",
          agentType: "new_product",
          status: "running",
          summary: "整理供应与工艺候选方案",
        },
      ],
    },
    {
      id: "proj_launch_val",
      createdAt: iso(now),
      updatedAt: iso(now),
      type: "new_product_project",
      name: "情人节礼盒首发",
      stage: "launch_validation",
      owner: "u_growth_lead",
      stakeholders: [
        {
          id: "u_gd",
          name: "运营与营销总监",
          role: "growth_director",
        },
      ],
      priority: 85,
      health: "watch",
      riskLevel: "medium",
      targetSummary: "首周达成预定转化目标",
      statusSummary: "首发第 3 天，转化略低于预期",
      latestPulse: "内容页 CTR 下滑，待确认是否微调主图",
      kpis: {
        updatedAt: iso(now),
        metrics: [
          {
            key: "cvr",
            label: "转化率",
            value: 1.8,
            unit: "%",
            trend: "down",
            freshness: "real_time",
          },
        ],
      },
      expression: {
        id: "expr_launch_1",
        createdAt: iso(now),
        updatedAt: iso(now),
        projectId: "proj_launch_val",
        contentBrief: "情感向种草 + 限时礼遇",
        visualBrief: "双主图 A/B",
        readinessStatus: "launched",
        creativeVersions: [
          {
            id: "cv_launch_a",
            createdAt: iso(now),
            updatedAt: iso(now),
            projectId: "proj_launch_val",
            name: "主图 A 礼遇版",
            type: "hero_image",
            status: "testing",
          },
          {
            id: "cv_launch_b",
            createdAt: iso(now),
            updatedAt: iso(now),
            projectId: "proj_launch_val",
            name: "主图 B 场景版",
            type: "hero_image",
            status: "draft",
          },
        ],
        recommendedDirection: "强化礼盒场景图",
      },
      actions: [
        baseAction("act_launch_1", "proj_launch_val", "launch_validation", {
          title: "主图微调批价",
          summary: "建议替换 B 版主图，待审批",
          approvalStatus: "pending",
        }),
      ],
      agentStates: [
        {
          id: "ag_launch_1",
          createdAt: iso(now),
          updatedAt: iso(now),
          projectId: "proj_launch_val",
          agentType: "diagnosis",
          status: "running",
          summary: "监控首发漏斗与舆情",
        },
      ],
    },
    {
      id: "proj_demo_growth",
      createdAt: iso(now),
      updatedAt: iso(now),
      type: "growth_optimization_project",
      name: "爆款 A 增长战",
      stage: "growth_optimization",
      owner: "u_growth_director",
      stakeholders: [
        {
          id: "u_gd",
          name: "运营与营销总监",
          role: "growth_director",
        },
      ],
      priority: 88,
      health: "at_risk",
      riskLevel: "high",
      targetSummary: "30 日内拉升 CVR，控制退款率",
      statusSummary: "关键调价待您审批，智能体已生成候选方案",
      latestPulse: "待审批：促销档位 B；异常：客服负面反馈上升",
      kpis: {
        updatedAt: iso(now),
        metrics: [
          {
            key: "cvr",
            label: "转化率",
            value: 2.1,
            unit: "%",
            trend: "down",
            freshness: "real_time",
          },
        ],
      },
      decisionObject: {
        id: "dec_growth_1",
        createdAt: iso(now),
        updatedAt: iso(now),
        projectId: "proj_demo_growth",
        stage: "growth_optimization",
        problemOrOpportunity: "转化下滑伴随差评抬头",
        rationale: "价格弹性与客服话术的联合影响",
        options: [
          {
            id: "opt_a",
            title: "温和降价 + 赠品",
            summary: "小幅降价锁定转化",
            expectedImpact: "CVR +0.3pt 预估",
            risk: "medium",
            resourcesNeeded: "营销预算 3%",
            validationWindow: "7 天",
            autoExecutable: false,
          },
          {
            id: "opt_b",
            title: "维持价盘 + 话术",
            summary: "优化客服话术与详情页证明点",
            expectedImpact: "差评率受控",
            risk: "low",
            resourcesNeeded: "内容运营 5 人日",
            validationWindow: "10 天",
            autoExecutable: false,
          },
        ],
        confidence: "medium",
        requiresHumanApproval: true,
        evidencePack: {
          refs: [
            {
              id: "ev_1",
              type: "metric",
              summary: "近 7 日 CVR 环比下降",
            },
          ],
        },
      },
      actions: [
        baseAction("act_g_1", "proj_demo_growth", "growth_optimization", {
          title: "促销档位 B 上架",
          summary: "组合券与满减对齐竞品",
          approvalStatus: "pending",
          risk: "high",
        }),
      ],
      agentStates: [
        {
          id: "ag_2",
          createdAt: iso(now),
          updatedAt: iso(now),
          projectId: "proj_demo_growth",
          agentType: "diagnosis",
          status: "waiting_human",
          summary: "待审批的增长实验组合",
          waitingReason: "high_risk_pricing_change",
        },
      ],
    },
    {
      id: "proj_legacy",
      createdAt: iso(now),
      updatedAt: iso(now),
      type: "legacy_upgrade_project",
      name: "经典款卫衣焕新",
      stage: "legacy_upgrade",
      owner: "u_rd_lead",
      stakeholders: [
        { id: "u_vis", name: "视觉总监", role: "visual_director" },
      ],
      priority: 55,
      health: "healthy",
      riskLevel: "low",
      targetSummary: "面料升级 + 主图统一",
      statusSummary: "打样已通过，待排期拍摄",
      kpis: {
        updatedAt: iso(now),
        metrics: [],
      },
      expression: {
        id: "expr_legacy_1",
        createdAt: iso(now),
        updatedAt: iso(now),
        projectId: "proj_legacy",
        readinessStatus: "in_progress",
        visualBrief: "统一主图规范与面料卖点可视化",
        creativeVersions: [
          {
            id: "cv_legacy_1",
            createdAt: iso(now),
            updatedAt: iso(now),
            projectId: "proj_legacy",
            name: "卫衣主图焕新 V1",
            type: "hero_image",
            status: "draft",
          },
        ],
      },
      actions: [],
      agentStates: [],
    },
    {
      id: "proj_review_cap",
      createdAt: iso(now),
      updatedAt: iso(now),
      type: "growth_optimization_project",
      name: "618 大促复盘包",
      stage: "review_capture",
      owner: "u_growth_lead",
      stakeholders: [{ id: "u_ceo", name: "老板", role: "ceo" }],
      priority: 60,
      health: "watch",
      riskLevel: "low",
      targetSummary: "沉淀可复用打法与 SOP",
      statusSummary: "复盘访谈已完成，待结构化为资产",
      kpis: {
        updatedAt: iso(now),
        metrics: [],
      },
      review: {
        id: "rev_618",
        createdAt: iso(now),
        updatedAt: iso(now),
        projectId: "proj_review_cap",
        verdict: "partial_success",
        resultSummary: "GMV 达标，利润率略低",
        attributionSummary: "流量结构变化与券力度过大",
        attributionFactors: [
          {
            id: "att_1",
            category: "campaign",
            summary: "券门槛设置偏低，核销快于预期",
            impactLevel: "high",
            controllable: true,
          },
          {
            id: "att_2",
            category: "timing",
            summary: "节奏上提前放量，挤压利润缓冲",
            impactLevel: "medium",
            controllable: true,
          },
          {
            id: "att_3",
            category: "supply",
            summary: "爆品补货窗口偏紧，临时调拨成本上升",
            impactLevel: "medium",
            controllable: false,
          },
        ],
        lessonsLearned: [
          "大促前需锁定券预算上限并与利润模拟联动",
          "爆品需预留安全库存与调拨预案",
        ],
        recommendations: [
          "双档券（引流/利润）分层，避免单一券型拉低毛利",
          "下一轮大促 T-14 固定「利润红线」评审门禁",
        ],
      },
      assetCandidates: [
        {
          id: "cand_618_sop",
          createdAt: iso(now),
          updatedAt: iso(now),
          projectId: "proj_review_cap",
          type: "sop",
          title: "大促券档分层与审批 SOP 候选",
          rationale: "由复盘智能体从审批链与券档表抽取，待经营确认后入库",
          approvalStatus: "pending",
          applicability: "同级别大促（双旦/周年庆）",
        },
        {
          id: "cand_618_rule",
          createdAt: iso(now),
          updatedAt: iso(now),
          projectId: "proj_review_cap",
          type: "rule",
          title: "利润率低于阈值时禁止再加券力度",
          rationale: "AI 规则草案；已标记为低摩擦自动校验候选",
          approvalStatus: "not_required",
        },
        {
          id: "cand_618_tpl",
          createdAt: iso(now),
          updatedAt: iso(now),
          projectId: "proj_review_cap",
          type: "template",
          title: "大促前利润模拟表模板",
          rationale: "从本次测算表抽象，需法务/财务口径确认",
          approvalStatus: "pending",
        },
        {
          id: "cand_618_skill",
          createdAt: iso(now),
          updatedAt: iso(now),
          projectId: "proj_review_cap",
          type: "skill",
          title: "「券+投放」联合诊断技能包",
          rationale: "沉淀智能体 Few-shot 与工具编排提示",
          approvalStatus: "pending",
        },
        {
          id: "cand_618_case",
          createdAt: iso(now),
          updatedAt: iso(now),
          projectId: "proj_review_cap",
          type: "case",
          title: "618 服饰类目券促案例骨架",
          rationale: "结构化案例字段已自动生成，待补定性访谈",
          approvalStatus: "not_required",
        },
        {
          id: "cand_618_eval",
          createdAt: iso(now),
          updatedAt: iso(now),
          projectId: "proj_review_cap",
          type: "evaluation_sample",
          title: "大促复盘问答题评测样本",
          rationale: "用于检验经营助理对归因与资产提炼的一致性",
          approvalStatus: "pending",
        },
      ],
      publishedAssets: [
        {
          id: "pub_618_case",
          createdAt: iso(now),
          updatedAt: iso(now),
          type: "case",
          title: "去年双11 券促对照案例（正式库）",
          summary: "已入库，可作为本年对照基线",
          sourceProjectId: "proj_review_cap",
          reuseCount: 3,
          status: "published",
        },
        {
          id: "pub_618_rule_old",
          createdAt: iso(now),
          updatedAt: iso(now),
          type: "rule",
          title: "券面额环比上调需二级审批（旧版）",
          summary: "已被新规则替代，保留可追溯",
          sourceProjectId: "proj_review_cap",
          status: "deprecated",
        },
      ],
      actions: [],
      agentStates: [
        {
          id: "ag_rev_1",
          createdAt: iso(now),
          updatedAt: iso(now),
          projectId: "proj_review_cap",
          agentType: "review_capture",
          status: "idle",
          summary: "等待复盘结论定稿后提取资产",
        },
      ],
    },
    {
      id: "proj_m2_full",
      createdAt: iso(now),
      updatedAt: iso(now),
      type: "new_product_project",
      name: "M2 全量字段演示项目",
      stage: "new_product_incubation",
      owner: "u_rd_lead",
      stakeholders: [
        { id: "u_rd", name: "产品研发总监", role: "product_rd_director" },
        { id: "u_vis", name: "视觉总监", role: "visual_director" },
      ],
      priority: 50,
      health: "watch",
      riskLevel: "medium",
      targetSummary: "用于详情页骨架联调",
      statusSummary: "聚合决策、定义、表达、动作、复盘与资产字段",
      latestPulse: "仅供演示，非真实经营数据",
      kpis: {
        updatedAt: iso(now),
        metrics: [
          {
            key: "launch_score",
            label: "综合分",
            value: 70,
            unit: "score",
            trend: "flat",
            freshness: "batch",
          },
        ],
      },
      opportunitySignals: [
        {
          id: "os_1",
          type: "demand_cluster",
          summary: "社媒话题热度上升",
          strength: 72,
          freshness: "near_real_time",
        },
      ],
      opportunityAssessment: {
        businessValueScore: 68,
        feasibilityScore: 75,
        expressionPotentialScore: 80,
        confidence: "medium",
        recommendation: "initiate",
      },
      decisionObject: {
        id: "dec_full_1",
        createdAt: iso(now),
        updatedAt: iso(now),
        projectId: "proj_m2_full",
        stage: "new_product_incubation",
        problemOrOpportunity: "是否加码该系列产能",
        rationale: "需求信号与供应链窗口匹配",
        options: [
          {
            id: "o1",
            title: "小批快反",
            summary: "先下试单",
            expectedImpact: "降低库存风险",
            risk: "low",
            resourcesNeeded: "产线 2 周",
            validationWindow: "14 天",
            autoExecutable: false,
          },
          {
            id: "o2",
            title: "观望一周",
            summary: "等待渠道数据再定",
            expectedImpact: "节省当期产能占用",
            risk: "medium",
            resourcesNeeded: "分析 3 人日",
            validationWindow: "7 天",
            autoExecutable: true,
          },
        ],
        recommendedOptionId: "o1",
        confidence: "high",
        requiresHumanApproval: true,
        evidencePack: { refs: [] },
      },
      definition: {
        id: "def_full_1",
        createdAt: iso(now),
        updatedAt: iso(now),
        projectId: "proj_m2_full",
        positioning: "演示定位",
        targetAudience: "演示人群",
        keySellingPoints: ["演示卖点 A"],
        priceBand: "待定",
        specsSummary: "演示规格",
        feasibilityRisk: "medium",
        samplingStatus: "in_progress",
      },
      expression: {
        id: "expr_full_1",
        createdAt: iso(now),
        updatedAt: iso(now),
        projectId: "proj_m2_full",
        readinessStatus: "in_progress",
        creativeVersions: [
          {
            id: "cv_1",
            createdAt: iso(now),
            updatedAt: iso(now),
            projectId: "proj_m2_full",
            name: "主图 V1",
            type: "hero_image",
            status: "draft",
          },
          {
            id: "cv_2",
            createdAt: iso(now),
            updatedAt: iso(now),
            projectId: "proj_m2_full",
            name: "主图 V2 极简",
            type: "hero_image",
            status: "testing",
          },
        ],
      },
      review: {
        id: "rev_full_1",
        createdAt: iso(now),
        updatedAt: iso(now),
        projectId: "proj_m2_full",
        verdict: "observe_more",
        resultSummary: "演示复盘摘要",
        attributionSummary: "演示归因",
        attributionFactors: [],
        lessonsLearned: [],
        recommendations: [],
      },
      assetCandidates: [
        {
          id: "ac_full_1",
          createdAt: iso(now),
          updatedAt: iso(now),
          projectId: "proj_m2_full",
          type: "template",
          title: "演示模板候选",
          rationale: "占位",
          approvalStatus: "not_required",
        },
      ],
      publishedAssets: [
        {
          id: "pub_full_1",
          createdAt: iso(now),
          updatedAt: iso(now),
          type: "rule",
          title: "演示已入库规则",
          summary: "占位",
          sourceProjectId: "proj_m2_full",
          status: "published",
        },
      ],
      actions: [
        baseAction("act_full_1", "proj_m2_full", "new_product_incubation", {
          title: "演示待审批动作",
          summary: "占位",
          approvalStatus: "pending",
        }),
        baseAction("act_full_run", "proj_m2_full", "new_product_incubation", {
          title: "智能体编排合并待办",
          summary: "场景智能体执行中",
          approvalStatus: "approved",
          executionStatus: "in_progress",
          executionMode: "agent",
          triggeredBy: "scenario_agent",
        }),
        baseAction("act_full_auto", "proj_m2_full", "new_product_incubation", {
          title: "规则同步库存水位",
          summary: "自动化批处理已完成",
          approvalStatus: "approved",
          executionStatus: "completed",
          executionMode: "automation",
          triggeredBy: "automation_rule",
          risk: "low",
        }),
        baseAction("act_full_done", "proj_m2_full", "new_product_incubation", {
          title: "样品寄送复核",
          summary: "人工已确认签收",
          approvalStatus: "approved",
          executionStatus: "completed",
          executionMode: "manual",
          triggeredBy: "human",
          risk: "low",
        }),
        baseAction("act_full_rollback", "proj_m2_full", "new_product_incubation", {
          title: "内容物料发布",
          summary: "口径变更回滚",
          approvalStatus: "approved",
          executionStatus: "rolled_back",
          executionMode: "manual",
          triggeredBy: "human",
          risk: "medium",
        }),
      ],
      approvals: [
        {
          id: "ar_full_1",
          createdAt: iso(now),
          updatedAt: iso(now),
          actionId: "act_full_done",
          approver: "产品研发总监",
          status: "approved",
          reason: "样品签收无误",
        },
      ],
      executionLogs: [
        {
          id: "elog_full_1",
          createdAt: iso(now),
          updatedAt: iso(now),
          actionId: "act_full_run",
          actorType: "agent",
          actorId: "ag_full_1",
          status: "in_progress",
          summary: "智能体：合并多源待办并排队",
        },
        {
          id: "elog_full_2",
          createdAt: iso(now),
          updatedAt: iso(now),
          actionId: "act_full_auto",
          actorType: "automation",
          actorId: "rule_inventory",
          status: "completed",
          summary: "自动化：库存水位已回写",
        },
        {
          id: "elog_full_3",
          createdAt: iso(now),
          updatedAt: iso(now),
          actionId: "act_full_rollback",
          actorType: "human",
          actorId: "u_rd",
          status: "rolled_back",
          summary: "审计：因口径变更触发回滚",
        },
      ],
      agentStates: [
        {
          id: "ag_full_1",
          createdAt: iso(now),
          updatedAt: iso(now),
          projectId: "proj_m2_full",
          agentType: "new_product",
          status: "running",
          summary: "演示智能体运行中",
        },
      ],
    },
  ];
}

const MOCK_PROJECTS: ProjectObject[] = buildSeedProjects();

export function createMockProjects(): ProjectObject[] {
  return MOCK_PROJECTS;
}

export function getProjectById(id: string): ProjectObject | undefined {
  return MOCK_PROJECTS.find((p) => p.id === id);
}

export const ROLE_LABELS: Record<RoleView, string> = {
  ceo: "老板",
  product_rd_director: "产品研发总监",
  growth_director: "运营与营销总监",
  visual_director: "视觉总监",
};
